//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectDBSQLServer.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbISP19AEntities : DbContext
    {
        private static dbISP19AEntities _context; //приватное статичное поле контекст
        public dbISP19AEntities()
            : base("name=dbISP19AEntities")
        {
        }
    
        public static dbISP19AEntities GetContext()
        {
            if (_context == null)
                _context = new dbISP19AEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
